FROM node:20-alpine

WORKDIR /app

# Copy package files and install deps once during image build
COPY ../nest_service/package*.json ./
RUN npm ci --legacy-peer-deps && npm cache clean --force

# Copy the full source code
COPY ../nest_service /app

EXPOSE 3000
CMD ["npm", "run", "start:dev"]